# Default colors
[colors.primary]
background = "#221d44"
foreground = "#c7c6d0"

[colors.cursor]
text = "#c7c6d0"
cursor = "#c7c6d0"
 

[colors]
# Normal colors
normal.black = "#221d44"
normal.red = "#D56DE5"
normal.green = "#7B83EA"
normal.yellow = "#9B95EE"
normal.blue = "#E793EE"
normal.magenta = "#C8AEF3"
normal.cyan = "#F2B6F2"
normal.white = "#c7c6d0"

# Bright colors
bright.black = "#6f6c84"
bright.red = "#D56DE5"
bright.green = "#7B83EA"
bright.yellow = "#9B95EE"
bright.blue = "#E793EE"
bright.magenta = "#C8AEF3"
bright.cyan = "#F2B6F2"
bright.white = "#c7c6d0"
